scan:
  dir: F:\temp
  keyword: EGFP
  interval: 1

img_proc:
  debug: True
  checkerboard: False
  checkerboard_row: 10
  checkerboard_col: 10
#  sigma1: 3
#  sigma2: 31
  block_size: 11
  tolerance: 100
  save_dir: F:\masks

tcpip:
  host: localhost
  port: 2222
  port_trigger: 2228
  trigger_name: tcp