scan:
  dir: F:\temp
  keyword: EGFP
  interval: 1
  timeout: 20

img_proc:
  debug: True
  checkerboard: False
  checkerboard_row: 10
  checkerboard_col: 10
#  sigma1: 3
#  sigma2: 31
  block_size: 11
  downscale: 4
  tolerance: 100
  wrad: 30
  save_dir: F:\masks

tcpip:
  host: localhost
  port: 2222
  port_trigger: 2228
  trigger_name: tcp